export type Lang = "en" | "fr";

export const strings = {
  en: {
    tagline: "A collection of personal projects — web apps, infra, and experiments.",
    status: "Not actively job hunting — open to interesting conversations.",
    notFoundSuffix: "does not exist.",
    projects: "Projects",
    infrastructure: "Infrastructure",
    infrastructureDesc: "Live infrastructure overview — k3s cluster, nodes, and pod routing.",
    postmortems: "Postmortems",
    updates: "Updates",
    all: "All",
    live: "Live ↗",
    source: "Source",
    footer: "Built with Next.js · Deployed on k3s",
    roleAll: "All",
    roleFrontend: "Frontend",
    roleBackend: "Backend",
    roleFullStack: "Full-stack",
    roleInfra: "Infra",
    aboutNav: "About",
    aboutTitle: "About",
    aboutText: [
      "I'm a bilingual full-stack developer with an AEC in Analyste Programmeur (Programmer Analyst) from LaSalle College.",
      "Before programming, I managed a Jean Coutu pharmacy and worked in photography and short films — different disciplines, but the same instinct: notice what's actually happening, not what's supposed to be happening. That's mostly what shows up on this site now: four live products, a homelab I run and occasionally break, and a public log of what went wrong and why.",
    ],
    backHome: "← Back home",
  },
  fr: {
    tagline: "Une collection de projets personnels — applications web, infra et expérimentations.",
    status: "Pas en recherche active d'emploi — ouvert aux discussions intéressantes.",
    notFoundSuffix: "n'existe pas.",
    projects: "Projets",
    infrastructure: "Infrastructure",
    infrastructureDesc: "Aperçu en direct de l'infrastructure — cluster k3s, nœuds et routage des pods.",
    postmortems: "Post-mortems",
    updates: "Mises à jour",
    all: "Tout",
    live: "En ligne ↗",
    source: "Source",
    footer: "Construit avec Next.js · Déployé sur k3s",
    roleAll: "Tout",
    roleFrontend: "Frontend",
    roleBackend: "Backend",
    roleFullStack: "Full-stack",
    roleInfra: "Infra",
    aboutNav: "À propos",
    aboutTitle: "À propos",
    aboutText: [
      "Je suis développeur full-stack bilingue, avec une AEC en Analyste Programmeur du Collège Lasalle.",
      "Avant la programmation, j'ai géré une pharmacie Jean Coutu et travaillé en photographie et courts métrages — des disciplines différentes, mais le même réflexe : remarquer ce qui se passe réellement, pas ce qui est censé se passer. C'est essentiellement ce qu'on retrouve sur ce site aujourd'hui : quatre produits en ligne, un homelab que je gère (et casse à l'occasion), et un journal public de ce qui a mal tourné et pourquoi.",
    ],
    backHome: "← Retour à l'accueil",
  },
} as const;
