export type Lang = "en" | "fr";

export const strings = {
  en: {
    tagline: "A collection of personal projects — web apps, infra, and experiments.",
    status: "Not actively job hunting — open to interesting conversations.",
    notFoundSuffix: "does not exist.",
    projects: "Projects",
    infrastructure: "Infrastructure",
    postmortems: "Postmortems",
    updates: "Updates",
    all: "All",
    nextPage: "Show more",
    prevPage: "Previous",
    nextPageArrow: "Next",
    allSkills: "All",
    noSkillMatches: "No updates tagged with this skill yet.",
    live: "Live ↗",
    source: "Source",
    footer: "Built with Next.js · Deployed on k3s",
    roleFullStack: "Full-stack",
    roleFrontend: "Frontend",
    roleBackend: "Backend",
    backendStatLatency: "live — pinged server-side, refreshes every 10s",
    backendStatResponse: "response time",
    backendStatStatus: "status",
    backendStatLive: "Live",
    backendStatEndpoints: "API endpoints",
    backendStatCommits: "commits",
    aboutNav: "About",
    aboutTitle: "About",
    aboutText: [
      "I'm a bilingual full-stack developer with an AEC in Analyste Programmeur (Programmer Analyst) from LaSalle College.",
      "Before programming, I managed a Jean Coutu pharmacy and worked in photography and short films — different disciplines, but the same instinct: notice what's actually happening, not what's supposed to be happening. That's mostly what shows up on this site now: four live products, a homelab I run and occasionally break, and a public log of what went wrong and why.",
    ],
    aboutProjectsTitle: "What's live",
    aboutStackTitle: "What I work with",
    backHome: "← Back home",
    infraStatNodes: "nodes online",
    infraStatPods: "pods running",
    infraStatK3sNodes: "k3s nodes",
    infraStatProjects: "live products",
    infraNetworkTitle: "Physical Network",
    infraNetworkDesc: "All physical machines sit behind OPNsense on a home LAN. Internet traffic leaving the homelab goes exclusively through a WireGuard VPN on the main server — nothing else has a direct outbound internet path.",
    infraTailscaleTitle: "Tailscale Overlay",
    infraTailscaleDesc: "Tailscale connects the remote nodes — a monitoring Pi and two cloud workers — back to the homelab without any firewall rules or VPN tunnels to configure. Every machine joins the same tailnet, reachable from anywhere as one flat private network.",
    infraK3sTitle: "k3s Cluster",
    infraK3sDesc: "A lightweight Kubernetes cluster spanning the homelab and cloud. The main server acts as control plane; two free-tier ARM workers provide enough capacity to run this site, several web apps, and supporting services.",
    infraRerouteHint: "Each request is served by one of three replicas — rotate to re-route and see which node picks it up.",
    infraServing: "← serving",
    infraTotal: "total",
    infraRunning: "running",
    infraPending: "pending",
    infraFailed: "failed",
  },
  fr: {
    tagline: "Une collection de projets personnels — applications web, infra et expérimentations.",
    status: "Pas en recherche active d'emploi — ouvert aux discussions intéressantes.",
    notFoundSuffix: "n'existe pas.",
    projects: "Projets",
    infrastructure: "Infrastructure",
    postmortems: "Post-mortems",
    updates: "Mises à jour",
    all: "Tout",
    nextPage: "Afficher plus",
    prevPage: "Précédent",
    nextPageArrow: "Suivant",
    allSkills: "Tout",
    noSkillMatches: "Aucune mise à jour pour cette compétence pour l'instant.",
    live: "En ligne ↗",
    source: "Source",
    footer: "Construit avec Next.js · Déployé sur k3s",
    roleFullStack: "Full-stack",
    roleFrontend: "Frontend",
    roleBackend: "Backend",
    backendStatLatency: "en direct — sondé côté serveur, actualisé toutes les 10s",
    backendStatResponse: "temps de réponse",
    backendStatStatus: "statut",
    backendStatLive: "En ligne",
    backendStatEndpoints: "points d'accès API",
    backendStatCommits: "commits",
    aboutNav: "À propos",
    aboutTitle: "À propos",
    aboutText: [
      "Je suis développeur full-stack bilingue, avec une AEC en Analyste Programmeur du Collège Lasalle.",
      "Avant la programmation, j'ai géré une pharmacie Jean Coutu et travaillé en photographie et courts métrages — des disciplines différentes, mais le même réflexe : remarquer ce qui se passe réellement, pas ce qui est censé se passer. C'est essentiellement ce qu'on retrouve sur ce site aujourd'hui : quatre produits en ligne, un homelab que je gère (et casse à l'occasion), et un journal public de ce qui a mal tourné et pourquoi.",
    ],
    aboutProjectsTitle: "En ligne",
    aboutStackTitle: "Avec quoi je travaille",
    backHome: "← Retour à l'accueil",
    infraStatNodes: "nœuds en ligne",
    infraStatPods: "pods actifs",
    infraStatK3sNodes: "nœuds k3s",
    infraStatProjects: "produits en ligne",
    infraNetworkTitle: "Réseau physique",
    infraNetworkDesc: "Toutes les machines physiques sont derrière OPNsense sur le réseau local. Le trafic sortant du homelab passe exclusivement par un VPN WireGuard sur le serveur principal — rien d'autre n'a d'accès internet direct.",
    infraTailscaleTitle: "Superposition Tailscale",
    infraTailscaleDesc: "Tailscale relie les nœuds distants — un Pi de monitoring et deux workers cloud — au homelab sans règles de pare-feu ni tunnels VPN à configurer. Chaque machine rejoint le même tailnet, accessible de partout comme un seul réseau privé.",
    infraK3sTitle: "Cluster k3s",
    infraK3sDesc: "Un cluster Kubernetes léger réparti entre le homelab et le cloud. Le serveur principal agit comme control plane; deux workers ARM gratuits fournissent assez de capacité pour ce site, plusieurs applications web et des services de support.",
    infraRerouteHint: "Chaque requête est servie par l'une des trois répliques — faites pivoter pour rediriger et voir quel nœud répond.",
    infraServing: "← répond",
    infraTotal: "total",
    infraRunning: "actifs",
    infraPending: "en attente",
    infraFailed: "échoués",
  },
} as const;
