apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - image-updater.yaml
  - networkpolicy.yaml

images:
  - name: jeanmichelbb/hub
    newTag: 523f2e19cfdd7cc0b6935595328f886bce3cd7e0
    newName: jeanmichelbb/hub
