apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - image-updater.yaml
  - networkpolicy.yaml

images:
  - name: jeanmichelbb/hub
    newTag: 0dd11494ecffa81ab90a98833a2a139d583cbe72
    newName: jeanmichelbb/hub
