apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - image-updater.yaml
  - networkpolicy.yaml

images:
  - name: jeanmichelbb/hub
    newTag: d3bf857f0464a1ca907f374a7114df07e2793d0c
    newName: jeanmichelbb/hub
